name: Build and deploy site
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mortenson/tome
    steps:
    - uses: actions/checkout@v2
    - name: Install Node
      run: |
        apt-get --allow-releaseinfo-change update
        curl -sL https://deb.nodesource.com/setup_18.x | bash -
        apt-get install -y nodejs
        nodejs -v
    - name: Install dependencies
      run: composer install
    - name: Install Tome
      run: ./vendor/drush/drush/drush tome:install -y
    - name: Run cron
      run: ./vendor/drush/drush/drush cron -l "https://andy.propertysyariah.biz.id"
    - name: Build search index
      run: LUNR_DRUSH=./vendor/bin/drush nodejs web/modules/contrib/lunr/js/index.node.js default
    - name: Build static site
      run: |
        ./vendor/drush/drush/drush tome:static -l "https://andy.propertysyariah.biz.id"
        ./vendor/drush/drush/drush cr
        ./vendor/drush/drush/drush tome:static-export-path /feed.xml -l "https://andy.propertysyariah.biz.id" --return-json
        ./vendor/drush/drush/drush tome:static-export-path /drupal-feed.xml -l "https://andy.propertysyariah.biz.id" --return-json
    - name: Copy CNAME
      run: cp CNAME ./html/
    - name: Copy 404 page
      run: cp ./html/404/index.html ./html/404.html
    - name: Deploy to GitHub pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: gh-pages-build
        publish_dir: ./html
        github_token: ${{ secrets.GITHUB_TOKEN }}