name: Build and deploy site
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mortenson/tome
    steps:
    - uses: actions/checkout@v2
    - name: Install Node
      run: |
        apt-get --allow-releaseinfo-change update
         curl -sL https://deb.nodesource.com/setup_18.x | bash -
         apt-get install -y nodejs
         node -v
    # - name: copy composer page1
    #   run: cp composer.json andyux01.github.io
    # - name: copy composer page
    #   run: cp ./andyux01.github.io/composer.json andyux01.github.io
    - name: Install dependencies di main
      run: composer install
    - name: Install Tome
      run: ./vendor/drush/drush/drush tome:install -y
    # Uncomment these lines if needed:
    - name: Generate sitemap
      run: ./vendor/drush/drush/drush simple-sitemap-generate -y -l "https://andy.propertysyariah.biz.id"
    # - name: Build search index
    #   run: LUNR_DRUSH=./vendor/drush/drush/drush nodejs web/modules/contrib/lunr/js/index.node.js default
    - name: Build static site
      run: ./vendor/drush/drush/drush tome:static -l "andy.propertysyariah.biz.id"
    # If you're pointing a custom domain to GitHub Pages, you probably need a CNAME file:
    # - name: Copy CNAME
    #   run: cp CNAME ./html/
    # GitHub pages also requires the 404 page to be in a particular path, uncomment if needed:
    - name: Copy 404 page
      run: cp ./docs/404/index.html ./docs/404.html
    - name: Deploy to GitHub pages
      uses: peaceiris/actions-gh-pages@v2
      env:
        PUBLISH_BRANCH: gh-pages-build
        PUBLISH_DIR: ./docs
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        emptyCommits: false
